<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2021-04-11T18:19:26+02:00" hostname="https://data-page-19352-dev-ed.cs101.my.salesforce.com" tests="1" failures="1"  errors="0"  time="4.96">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Apr 11, 2021 6:19 PM"/>
            <property name="testExecutionTime" value="4.96 s"/>
            <property name="testTotalTime" value="4.96 s"/>
            <property name="commandTime" value="8.78 s"/>
            <property name="hostname" value="https://data-page-19352-dev-ed.cs101.my.salesforce.com"/>
            <property name="orgId" value="00D1X00000034R1UAI"/>
            <property name="username" value="test-in7nqa4fsmgt@example.com"/>
            <property name="testRunId" value="7071X00001WrQ23"/>
            <property name="userId" value="0051X000007SSFeQAO"/>
        </properties>
        <testcase name="should_aggregate_two_orders_on_account" classname="TestUpdateAccountTurnover" time="4.96">
            <failure message="System.AssertException: Assertion Failed: Expected: 100, Actual: 200"><![CDATA[Class.TestUpdateAccountTurnover.should_aggregate_two_orders_on_account: line 133, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
