<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2021-04-09T18:45:54+02:00" hostname="https://data-java-1583-dev-ed.cs101.my.salesforce.com/" tests="1" failures="1"  errors="0"  time="0.91">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Apr 9, 2021 6:45 PM"/>
            <property name="testExecutionTime" value="0.91 s"/>
            <property name="testTotalTime" value="0.91 s"/>
            <property name="commandTime" value="4.28 s"/>
            <property name="hostname" value="https://data-java-1583-dev-ed.cs101.my.salesforce.com/"/>
            <property name="orgId" value="00D1X0000002tFWUAY"/>
            <property name="username" value="test-grt3b54ezt0d@example.com"/>
            <property name="testRunId" value="7071X00001WeC4k"/>
            <property name="userId" value="0051X000007M7fFQAS"/>
        </properties>
        <testcase name="should_aggregate_two_orders_on_account" classname="TestUpdateAccountTurnover" time="0.91">
            <failure message="System.AssertException: Assertion Failed: Expected: 21500, Actual: null"><![CDATA[Class.TestUpdateAccountTurnover.should_aggregate_two_orders_on_account: line 62, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
