<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2021-04-14T11:08:59+02:00" hostname="https://data-page-19352-dev-ed.cs101.my.salesforce.com" tests="1" failures="1"  errors="0"  time="4.1">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Apr 14, 2021 11:08 AM"/>
            <property name="testExecutionTime" value="4.1 s"/>
            <property name="testTotalTime" value="4.1 s"/>
            <property name="commandTime" value="6.41 s"/>
            <property name="hostname" value="https://data-page-19352-dev-ed.cs101.my.salesforce.com"/>
            <property name="orgId" value="00D1X00000034R1UAI"/>
            <property name="username" value="test-in7nqa4fsmgt@example.com"/>
            <property name="testRunId" value="7071X00001XHV2p"/>
            <property name="userId" value="0051X000007SSFeQAO"/>
        </properties>
        <testcase name="should_populate_account_chiffreAffaire" classname="TestUpdateAccountBatch" time="4.1">
            <failure message="System.AssertException: Assertion Failed: Expected: 1500, Actual: 0"><![CDATA[Class.TestUpdateAccountBatch.should_populate_account_chiffreAffaire: line 109, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
